var employees = JSON.parse(localStorage.getItem('employees')) || [
  {"id":27, "unit": "Arzignano", "name": "mcracco", "requests": [] },
  {"id":42, "unit": "Arzignano", "name": "speripoli", "requests": [] },
  {"id":43, "unit": "Arzignano", "name": "speripolli", "requests": [] },
  {"id":35, "unit": "Arzignano", "name": "probinelli", "requests": [] },
  {"id":37, "unit": "Arzignano", "name": "rrobinelli", "requests": [] },
  {"id":29, "unit": "Arzignano", "name": "mtomasi", "requests": [] },
  {"id":31, "unit": "Montecchio", "name": "palberti", "requests": [] },
  {"id":11, "unit": "Montecchio", "name": "acecchetto", "requests": [] },
  {"id":18, "unit": "Montecchio", "name": "ecerisara", "requests": [] },
  {"id":26, "unit": "Montecchio", "name": "mcolombara", "requests": [] },
  {"id":14, "unit": "Montecchio", "name": "cconsolaro", "requests": [] },
  {"id":39, "unit": "Montecchio", "name": "sebanetti", "requests": [] },
  {"id":21, "unit": "Montecchio", "name": "ffacci", "requests": [] },
  {"id":15, "unit": "Montecchio", "name": "clovato", "requests": [] },
  {"id":34, "unit": "Montecchio", "name": "pmarchioro", "requests": [
    {"id":24,"fromdate":"2018-02-26T10:00:00","todate":"2018-02-26T15:00:00","type":"type1","status":3},
    {"id":25,"fromdate":"2018-02-27T10:00:00","todate":"2018-02-27T17:00:00","type":"type2","status":3},
  ]},
  {"id":41, "unit": "Montecchio", "name": "snicoletti", "requests": [
    {"id":8,"fromdate":"2018-02-15T08:30:00","todate":"2018-02-15T09:15:00","type":"type1","status":2},
    {"id":9,"fromdate":"2018-02-15T14:00:00","todate":"2018-02-15T14:45:00","type":"type2","status":2},
  ] },
  {"id":36, "unit": "Montecchio", "name": "rposenato", "requests": [] },
  {"id":25, "unit": "Montecchio", "name": "grizzo", "requests": [] },
  {"id":28, "unit": "Montecchio", "name": "mromio", "requests": [] },
  {"id":17, "unit": "Montecchio", "name": "dvisentin", "requests": [] },
  {"id":30, "unit": "Montecchio", "name": "mzanella", "requests": [] },
  {"id":10, "unit": "Schio", "name": "aadriani", "requests": [] },
  {"id":32, "unit": "Schio", "name": "pbonato", "requests": [] },
  {"id":214, "unit": "Schio", "name": "acaron", "requests": [] },
  {"id":38, "unit": "Schio", "name": "scomparin", "requests": [] },
  {"id":16, "unit": "Schio", "name": "ddallaguarda", "requests": [] },
  {"id":23, "unit": "Schio", "name": "ggalliazzo", "requests": [] },
  {"id":22, "unit": "Schio", "name": "fgolo", "requests": [] },
  {"id":33, "unit": "Schio", "name": "pguidotti", "requests": [] },
  {"id":40, "unit": "Schio", "name": "slosare", "requests": [] },
  {"id":24, "unit": "Schio", "name": "gmaino", "requests": [] },
  {"id":12, "unit": "Schio", "name": "apento", "requests": [] },
  {"id":19, "unit": "Schio", "name": "eperazzolo", "requests": [] },
  {"id":216, "unit": "Schio", "name": "epizzolotto", "requests": [] },
  {"id":20, "unit": "Schio", "name": "eriva", "requests": [] },
  {"id":213, "unit": "Schio", "name": "csossan", "requests": [] },
  {"id":44, "unit": "Schio", "name": "sspiller", "requests": [] },
  {"id":212, "unit": "Schio", "name": "mvisona", "requests": [] },
  {"id":13, "unit": "Schio", "name": "azordan", "requests": [] },
];
